package debr.myBatis.dao;

import debr.myBatis.model.Sponsor;
import java.util.List;

public interface SponsorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SPONSOR
     *
     * @mbg.generated Tue Mar 03 22:48:23 EET 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SPONSOR
     *
     * @mbg.generated Tue Mar 03 22:48:23 EET 2020
     */
    int insert(Sponsor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SPONSOR
     *
     * @mbg.generated Tue Mar 03 22:48:23 EET 2020
     */
    Sponsor selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SPONSOR
     *
     * @mbg.generated Tue Mar 03 22:48:23 EET 2020
     */
    List<Sponsor> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SPONSOR
     *
     * @mbg.generated Tue Mar 03 22:48:23 EET 2020
     */
    int updateByPrimaryKey(Sponsor record);
}